### ISSUE TITLE
Support for File Type ?

### ISSUE THREAD

**Issue by S3bb1** [atlantishealthcare/swagger-model-validator#83]
What about checks for Type "File" in Swagger ?

**Comment by brodyd** [comment]
Generally files are passed in as Parameters and not as Body contents.  By the time the body gets to the validator I'm not sure that the file is in it anymore.  I believe it is arranged between the client and the Server.  The Model-Validator wouldn't see any file parts because they are in the method definition.

I could be quite wrong though.  I'd be happy to take a definition and a request for testing.
